# Generated by Django 5.2.6 on 2025-09-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivation',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='outcomes',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
