# Generated by Django 5.2.6 on 2025-09-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_student_id_motivation_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
