# Generated by Django 5.2.6 on 2025-09-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_motivation_student_alter_outcomes_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
