# Generated by Django 5.2.6 on 2025-09-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_motivation_student_alter_outcomes_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aim',
            name='aim',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='outcomes',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='skill_level',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.CharField(),
        ),
    ]
