# Generated by Django 5.2.6 on 2025-09-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_agerange_age_range_alter_agerange_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilllevel',
            old_name='skills_description',
            new_name='skill_description',
        ),
    ]
