# Generated by Django 5.2.6 on 2025-09-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_available', models.CharField()),
            ],
        ),
    ]
