# Generated by Django 5.2.6 on 2025-09-09 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_hoursavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hours_available',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.hoursavailable'),
            preserve_default=False,
        ),
    ]
