# Generated by Django 5.2.6 on 2025-09-13 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_student_hours_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.experience')),
                ('hours_available', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hoursavailable')),
                ('outcomes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outcomes')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.referral')),
                ('registration_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registration')),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skilllevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track')),
            ],
        ),
    ]
